<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bkscr</string>
	</array>
	<key>name</key>
	<string>BKEngine Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.other.link.bks</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bks</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.storage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)\*(\s*)(?:(register|main)|(\w+))</string>
			<key>name</key>
			<string>label.bks</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[(\s*)(?:(import|macro|return(?:to)?|if|else(?:if)?|endif|for|continue|break|next)|(\w+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bks</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.bks</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>instruction.square.bks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\@(\s*)(?:(import|macro|return(?:to)?|if|else(?:if)?|endif|for|continue|break|next)|(\w+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bks</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.bks</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>instruction.line.bks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)#(?=[^#])</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>bkscript.line.bks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#raw_code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^##+</string>
			<key>end</key>
			<string>^##+</string>
			<key>name</key>
			<string>bkscript.block.bks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#raw_code</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.bks</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>/* ..... */</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.bks</string>
		</dict>
		<key>boolean</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\btrue\b</string>
					<key>name</key>
					<string>constant.language.boolean.true.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfalse\b</string>
					<key>name</key>
					<string>constant.language.boolean.false.bks</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
		<key>double_quoted_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.bks</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.bks</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.bks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.bks</string>
				</dict>
			</array>
		</dict>
		<key>instruction_api</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(sprite(opt)?|addto|layer|remove(all)?|((info|button|slider|checkbox)(ex)?)|anchor|zorder|bgm|se|voice|stop|volume|pause|resume|fade|(text(cursor|window|on|off|speed|style|tag|sprite)?)|locate|i|b|s|u|r|l|p|er|ruby|messagelayer|((store|restore)font)|action|eval|jump|call|return|returnto|if|else(if)?|endif|tablegoto|for|continue|break|next|(wait((all)?action|button|bgm|fade|trans|se|voice)?)|(stop((all)?action|(all)?trans))|click|inputbox|(pre)?trans|(delete)?event|quit|idlesp|history|fileexist|save(point|toimage)?|load|screenshot)\b</string>
					<key>name</key>
					<string>entity.name.tag.bks</string>
				</dict>
			</array>
		</dict>
		<key>instruction_attribute</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s+\w+</string>
					<key>name</key>
					<string>entity.other.attribute-name.bks</string>
				</dict>
			</array>
		</dict>
		<key>instruction_content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(basic_layer|message_layer)\b</string>
					<key>name</key>
					<string>support.constant.bks</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bks</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\s*)=(\s*)</string>
					<key>name</key>
					<string>keyword.operator.bks</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>array.bks</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>instruction_special_api</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(macro|import)\b</string>
					<key>name</key>
					<string>entity.name.tag.special.bks</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.bks</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>// .....</string>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.bks</string>
		</dict>
		<key>line_comment2</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.bks</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>; ......</string>
			<key>match</key>
			<string>^(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.colon.bks</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.bks</string>
		</dict>
		<key>raw_code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var|number|char|string|array|dictionary|class)\b</string>
					<key>name</key>
					<string>storage.type.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(global|propset|delete)\b</string>
					<key>name</key>
					<string>storage.modifier.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|\-|\*|/|%|^|&amp;&amp;|\|\||!|\+\+|\-\-|=|\+=|\-=|\*=|/=|%=|\^=|&lt;|&gt;|==|!=|&lt;=|&gt;=|\||&amp;|:|=&gt;</string>
					<key>name</key>
					<string>keyword.operator.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(for|foreach|in|if|else|do|while|return|break|continue|case)\b</string>
					<key>name</key>
					<string>keyword.control.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Date|Math|Regex|Script|System|SaveData|Channel|History|Sprite|Timer|DownloadManager|Json|Network)\b</string>
					<key>name</key>
					<string>support.class.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(log|typeof|print|eval|range|random|itoa|itoa2|time|hash|hash16|saveFile|loadFile|appendFile|evalFile|toString|fileExist)\b</string>
					<key>name</key>
					<string>support.function.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\;</string>
					<key>name</key>
					<string>punctuation.terminator.statement.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>meta.delimiter.method.period.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(|\)</string>
					<key>name</key>
					<string>meta.brace.round.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[|\]</string>
					<key>name</key>
					<string>meta.brace.square.bks</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\{|\}</string>
					<key>name</key>
					<string>meta.brace.curly.bks</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.bks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.bks</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.bks</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.bks</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.bks</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(function)\s+([a-zA-Z_$]\w*)?\s*(\()(.*?)(\))</string>
					<key>name</key>
					<string>meta.function.bks</string>
				</dict>
			</array>
		</dict>
		<key>single_quoted_string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.bks</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.bks</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.bks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.bks</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single_quoted_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double_quoted_string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bks</string>
	<key>uuid</key>
	<string>175fdd22-a5a7-4c19-ae73-70202832c212</string>
</dict>
</plist>
